receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
exporters:
  logging:
    loglevel: debug
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
